---
title: "clean-data"
author: "Stephen Uong"
date: "2024-08-27"
output: html_document
---
# Load libraries
```{r}
library(rio)
library(tidyverse)
library(lubridate)
library(tigris)
library(gganimate)
```

# Import data
```{r}
# Import fred data:
fred_prelim <- import("data/fred_data_pull.csv") %>% 
  as_tibble()

# Import/prep spatial data:
states_sf <- st_read("data/cb_2018_us_state_20m/cb_2018_us_state_20m.shp") %>% 
  # Figure out code to add inset for these states
  dplyr::filter(!NAME %in% c("Alaska", "Hawaii","Puerto Rico")) 
cbsa_sf_prelim <- core_based_statistical_areas()
cbsa_sf <- cbsa_sf_prelim %>% 
  dplyr::filter(str_detect(NAMELSAD, "(San Francisco)|(New York)")) %>% 
  st_centroid() 
cbsa_coord <- cbsa_sf %>% st_coordinates() %>% as_tibble() %>% 
  dplyr::rename(lon = X, lat = Y)
cbsa_name <- cbsa_sf %>% dplyr::pull(NAMELSAD) %>% 
  as_tibble_col(column_name = "msa") %>% 
  dplyr::mutate(msa = dplyr::case_when(
    msa %>% str_detect("New York") ~ "NY",
    msa %>% str_detect("San Francisco") ~ "SF"
  ))
cbsa_df <- bind_cols(cbsa_name, cbsa_coord) %>% 
  dplyr::mutate(msa)

```

# Clean data
```{r}
fred <- fred_prelim %>% 
  dplyr::select(-V1) %>% 
  dplyr::mutate(year = year(date)) %>% 
  dplyr::left_join(cbsa_df, by = "msa")
```

# Filter
```{r}
fred_filter <- fred
## Example:
# fred_filter <- fred %>% dplyr::filter(msa == "SF")
```


# Graphs
## By Time
```{r}
fred_filter %>% 
  ggplot(aes(x = year, y = value, color = msa)) +
  geom_line() +
  facet_grid(metric ~ ., scales = "free") +
  theme_bw() +
  labs(title = "Change Over Time", 
       x = "Year", y = "Value", color = "MSA") +
  theme(legend.position = "bottom",
        plot.title = element_text(hjust = 0.5, face = "bold"))
```

## By Area
```{r}
# To do:
  # add projection
  # add north arrow/scalebar

# Require: choose variable
# Conditional: choose year, but can animate over year

# Data prep
fred_map_static <- fred_filter %>% 
  dplyr::filter(year == 2000, metric == "CPI")
fred_map_anim <- fred_filter %>% 
  dplyr::filter(metric == "CPI")

# static map
ggplot() +
  geom_sf(data = states_sf, fill = "white") +
  geom_point(data = fred_map_static,
             aes(x = lon, y = lat, size = value),
             color = "skyblue", alpha = 0.2) +
  geom_text(data = fred_map_static, aes(x = lon, y = lat, label = msa),
            nudge_y = 1.5, nudge_x = -1) +
  theme_void() +
  labs(size = "Value") +
  theme(legend.position = "bottom")
# animated map
ggplot() +
  geom_sf(data = states_sf, fill = "white") +
  geom_point(data = fred_map_anim,
             aes(x = lon, y = lat, size = value),
             color = "skyblue", alpha = 0.2) +
  geom_text(data = fred_map_anim, aes(x = lon, y = lat, label = msa),
            nudge_y = 1.5, nudge_x = -1) +
  theme_void() +
  labs(title = "Year: {frame_time}", size = "Value") +
  theme(legend.position = "bottom") +
  transition_time(year)

```

